### ISSUE TITLE
[Bug] Weird behavior after click on color picker dropdown inside iframe

### ISSUE THREAD

**Issue by ducdhm** [itsjavi/bootstrap-colorpicker#157]
- Link JSFiddle: http://jsfiddle.net/bobkhin/69t2tov1/
- Context: 
  - I have an input inside an iframe. 
  - I initialized colorpicker for this input. 
  - After that, I clicked input for showing color picker dropdown for choosing a color
  - I click on outside of iframe, the color becomes to black
- Expected behaviour: Selected color is kept
- Actual behaviour: Selector color changed to black

**Comment by mjolnic** [comment]
JSFiddle adds your code into a iframe. Then you are creating another iframe inside that one. Maybe that's the problem. The mousemove events seems to get crazy and only clicked is allowed.

It seems a cross-domain issue : http://stackoverflow.com/questions/5261328/receive-mousemove-events-from-iframe-too

**Comment by ducdhm** [comment]
@mjolnic I have a page (it's in my local) which I create an iframe and initialize color picker inside this iframe. I also get the same problem.

**Comment by mjolnic** [comment]
@ducdhm Can you check again with latest version 2.3.3 ? It seems that the black color issue is not happening anymore, at least on the Fiddle.

**Comment by ducdhm** [comment]
@mjolnic I have tested with lastest version 2.3.3 and seems like it's not fixed. Maybe I'll find other solution for my project.

**Comment by mjolnic** [comment]
There might be something in your code that produces that, the issue cannot be reproduced in JSFiddle with the code you provided.

Anyway, if you find a solution and/or the cause of your problem could you post it here? thanks

**Comment by bkavuncu** [comment]
I experience this problem too, For example, I have an iframe on the right bottom corner of the page. I create my colorpicker inside an element in this iframe. The moment I move my mouse outside the iframe, the parent page acts like a giant colorpicker, where moving mouse around actually changes color of the colorpicker inside the iframe, even the color picker is disabled.

**Comment by agupta1989** [comment]
I faced the similar issue in my case as well. and I believe this issue is because of context in which color picker is executing. may be we need to provide some externalization of the default context. by default it should run within `window` or if provided it should take `iframe.window`. 

That is one thing, another thing is, as @ducdhm said, clicking outside of iframe still firing `colorChange` events repeatedly.
