### ISSUE TITLE
Does not work with jsRender

### ISSUE THREAD

**Issue by darmie** [itsjavi/bootstrap-colorpicker#165]
I tried using this color picker with jsRender but it doesn't work. 
I have the input tag in a jsRender template, but the color picker doesn't show. Is it because the content is loaded dynamically?

**Comment by mjolnic** [comment]
I don't know exactly how jsRender works but there may be some way to make it work with jQuery plugins that are rendered on the DOMContentLoaded event, like this one.

Isn't there a way to initialize this plugin after the template is rendered and the HTML is available on the DOM?

**Comment by mjolnic** [comment]
You also could provide an example using JSFiddle or similar, as it is specified here (and when you create a new issue) https://github.com/mjolnic/bootstrap-colorpicker/blob/master/CONTRIBUTING.md
