### ISSUE TITLE
Transparency with events

### ISSUE THREAD

**Issue by WansonSwanson** [itsjavi/bootstrap-colorpicker#172]
Not sure if there is already a fix for this but when I have a color changer that changes the background for a div, the transparency factor doesn't work. It converts the background color to rgb, but not rgba.

**Comment by carlosvidal** [comment]
Same problem here. SetValue don't work with RGBA

**Comment by itsjavi** [comment]
@WansonSwanson please could you provide an example as it's said in CONTRIBUTING.md ? Thanks

**Comment by carlosvidal** [comment]
`$("#myPicker").colorpicker('setValue', 'rgba(255,0,0,.5)');

$("#myPicker").colorpicker().on('changeColor', function(ev) {
       $("#pie").css({
       	"background-color" : $("#myPicker").colorpicker('getValue'),
       });
   });`

**Comment by emileber** [comment]
@carlosvidal it works for me. The only thing is that if the alpha was never set, it returns a hex value by default, even if the format has been specified otherwise.

To be sure, you could use the color object:

```
var $picker = $("#myPicker"),
    $pie = $("#pie");
$picker.colorpicker('setValue', 'rgba(255,0,0,.5)');

$picker.on('changeColor', function(ev) {
    var c = ev.color.toRGB(); // returns a RGBA hash
    $pie.css({
        "background-color": "rgba(" + c.r + ", " + c.g + ", " + c.b + ", " + c.a + ")",
    });
});
````

**Comment by carlosvidal** [comment]
Works perfectly. Thanks
