### ISSUE TITLE
Add typescript typings

### ISSUE THREAD

**Issue by akankov** [itsjavi/bootstrap-colorpicker#179]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/farbelous/bootstrap-colorpicker/issues/179)

Hello!

Why don't you create typescript typings for your plugin?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/farbelous/bootstrap-colorpicker/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by itsjavi** [comment]
Hi @akankov I am not a TypeScript developer. If you think that will bring some benefit to the plugin, feel free to collaborate ;)

**Comment by akankov** [comment]
ok

**Comment by CzBuCHi** [comment]
I made this for myself  but why not share :)
-
    interface BootstrapColorpickerOptionsSlider {
        maxLeft: number;
        maxTop: number;
        callLeft: string;
        callTop: string;
    }

    interface BootstrapColorpickerOptions {
        /**
         * If not false, forces the color format to be hex, rgb or rgba, otherwise the format is automatically detected.
         */
        format: string;
        /**
         * If not false, sets the color to this value.
         */
        color: string;
        /**
         * If not false, the picker will be contained inside this element, otherwise it will be appended to the document body.
         */
        container: string | JQuery;
        /**
         * Children selector for the component or element that trigger the colorpicker and which background color will change (needs an inner <i> element).
         */
        component: string | JQuery;
        /**
         * Children selector for the input that will store the picker selected value.
         */
        input: string | JQuery;
        /**
         * If true, the hue and alpha channel bars will be rendered horizontally, above the saturation selector.
         */
        horizontal: boolean;
        /**
         * If true, forces to show the colorpicker as an inline element.
         */
        inline: boolean;
        /**
         * Vertical sliders configuration
         */
        sliders: {
            saturation: BootstrapColorpickerOptionsSlider;
            hue: BootstrapColorpickerOptionsSlider;
            alpha: BootstrapColorpickerOptionsSlider;
        };
        /**
         * Horizontal sliders configuration
         */
        slidersHorz: {
            saturation: BootstrapColorpickerOptionsSlider;
            hue: BootstrapColorpickerOptionsSlider;
            alpha: BootstrapColorpickerOptionsSlider;
        };
        /**
         * Customizes the default colorpicker HTML template.
         */
        template: string;
        /**
         * By default, the colorpicker is aligned to the right of the input. If you need to switch it to the left, set align to 'left'.
         */
        align: string;
        /**
         * Adds this class to the colorpicker widget.
         */
        customClass: string;
        /**
         * List of pre selected colors (hex format). If you choose one of these colors, the alias is returned instead of the hex code.}
         */
        colorSelectors: { [colorName: string]: string };
    }

    interface BootstrapColorpicker {
        /**
         * Access to the colorpicker Color object information
         */
        color: BootstrapColorpickerColor;
    }

    interface BootstrapColorpickerEvent extends Event {
        color: BootstrapColorpickerColor;
    }

    interface BootstrapColorpickerColor {

        /**
         * Set a new color.The value is parsed and tries to do a quess on the format.
         */
        setColor(value: any): void;
        /**
         * Set the HUE with a value between 0 and 1.
         */
        setHue(value: number): void;
        /**
         * Set the saturation with a value between 0 and 1.
         */
        setSaturation(value: number): void;
        /**
         * Set the brightness with a value between 0 and 1.
         */
        setBrightness(value: number): void;
        /**
         * Set the transparency with a value between 0 and 1.
         */
        setAlpha(value: number): void;
        /**
         * Returns a hash with red, green, blue and alpha.
         */
        toRGB(h?: number, s?: number, b?: number, a?: number): { r: number; g: number; b: number; a: number; };
        /**
         * Returns a string with HEX format for the current color.
         */
        toHex(h?: number, s?: number, b?: number, a?: number): string;
        /**
         * Returns a hash with HSLA values.
         */
        toHSL(h?: number, s?: number, b?: number, a?: number): { h: number; s: number; l: number; a: number; };

        toAlias(r: number, g: number, b: number, a: number): string;
        RGBtoHSB(r: number, g: number, b: number, a: number): { h: number; s: number; b: number; a: number; };
        HueToRGB(p: number, q: number, h: number): number;
        HSLtoRGB(h: number, s: number, l: number, a: number): number[]; // [r,g,b,a]
        toString(format: 'rgb' | 'rgba' | 'hsl' | 'hsla' | 'hex' | 'alias'): string;
        colorNameToHex(name: string): string;
    }

    interface JQueryStatic {
        colorpicker: BootstrapColorpicker;
    }

    interface JQuery {

        /**
         * Initializes an colorpicker.
         */
        colorpicker(options: BootstrapColorpickerOptions): JQuery;
        /**
         * Gets the value from the input or the data attribute (if has no input), otherwise returns the default value, which defaults to #000000 if not specified.
         */
        colorpicker(method: 'getValue', defaultValue: string): String;
        /**
         * Set a new value for the color picker (also updates everything).Triggers 'changeColor' event.
         */
        colorpicker(method: 'setValue', value: string): void;
        /**
         * Show the color picker
         */
        colorpicker(method: 'show'): void;
        /**
         * Hide the color picker
         */
        colorpicker(method: 'hide'): void;
        /**
         * Updates the color picker's position relative to the element
         */
        colorpicker(method: 'reposition'): void;
        /**
         * Refreshes the widget colors (this is done automatically)
         */
        colorpicker(method: 'update'): void;
        /**
         * Enable the color picker.
         */
        colorpicker(method: 'enable'): void;
        /**
         * Disable the color picker.
         */
        colorpicker(method: 'disable'): void;
        /**
         * Destroys the colorpicker widget and unbind all .colorpicker events from the element and component
         */
        colorpicker(method: 'destroy'): void;

        /**
         * Access to the colorpicker API directly 
         */
        data(key: 'colorpicker'): BootstrapColorpicker;

        /**
         * This event fires immediately when the color picker is created.
         */
        on(events: 'create', selector?: string, data?: any, handler?: (eventObject: BootstrapColorpickerEvent) => any): JQuery;
        /**
         * This event fires immediately when the color picker is displayed.
         */
        on(events: 'showPicker', selector?: string, data?: any, handler?: (eventObject: BootstrapColorpickerEvent) => any): JQuery;
        /**
         * This event is fired immediately when the color picker is hidden.
         */
        on(events: 'hidePicker', selector?: string, data?: any, handler?: (eventObject: BootstrapColorpickerEvent) => any): JQuery;
        /**
         * This event is fired when the color is changed.
         */
        on(events: 'changeColor', selector?: string, data?: any, handler?: (eventObject: BootstrapColorpickerEvent) => any): JQuery;
        /**
         * This event is fired immediately when the color picker is disabled, except if it was initialized as disabled.
         */
        on(events: 'disable', selector?: string, data?: any, handler?: (eventObject: BootstrapColorpickerEvent) => any): JQuery;
        /**
         * This event is fired immediately when the color picker is enabled, except upon initialization.
         */
        on(events: 'enable', selector?: string, data?: any, handler?: (eventObject: BootstrapColorpickerEvent) => any): JQuery;
        /**
         * This event fires immediately when the color picker is destroyed.
         */
        on(events: 'destroy', selector?: string, data?: any, handler?: (eventObject: BootstrapColorpickerEvent) => any): JQuery;
    }

**Comment by itsjavi** [comment]
@CzBuCHi cool, where should this be added? could you do a PR with the needed file(s)/change(s) thanks!

**Comment by CzBuCHi** [comment]
no idea how to create PR :( ...

add this line to package.json: **"typings": "./bootstrap-colorpicker.d.ts",**
and create file **bootstrap-colorpicker.d.ts** in root: [bootstrap-colorpicker.d.ts.txt](https://github.com/itsjavi/bootstrap-colorpicker/files/678408/bootstrap-colorpicker.d.ts.txt)

PS: d.ts may need some editing (missing / incorrect doc, etc.)

**Comment by itsjavi** [comment]
Since `typings` has been apparently deprecated on TypeScript 2+, I will close this feature request.

**Comment by CzBuCHi** [comment]
u misunderstood that deprecation:
`typings` was npm package that was used for downloading d.ts files from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), in typescript 2 there was added simpler way to do the same by installing pseudo package from @types/* via npm (like `npm install @types/node` for example)

this is used for packages with dont have their own d.ts file (like yours)

u can still use "typings": "somefile.d.ts" in your package.json file and it will work fine

comunity can still send d.ts file to DefinitelyTyped but that will lead to inconsitencies between our package current api and d.ts file....

**Comment by itsjavi** [comment]
Ok still, unless there is an automated way to generate it I don't see the benefit of adding it and having to maintain it manually. Otherwise I would be happy to do it.

**Comment by stefan505** [comment]
@itsjavi the benefit you are missing is reach IMO. More and more applications are developed in TypeScript and typings are essential for various reasons. I would have used this plugin in my TypeScript-based wep app if it had typings.

**Comment by itsjavi** [comment]
any volunteer to add this in a PR, will be welcome

**Comment by ilsergente1993** [comment]
I'm adding a comment since the ts typings are really needed for people that use this plugin for industrial web applications using the last technologies such as Aurelia or similar.

**Comment by mustafasalahuldin** [comment]
I have problem compiling the package as it seems like some dependencies have been depreciated.
I also need a non-webpack compiled version in  order to make it work well with the ts definition.

**Comment by itsjavi** [comment]
I am closing this issue. 

It's from 2016 and no one has proposed a Pull Request to maintain this.
