### ISSUE TITLE
how to store selected rgb value

### ISSUE THREAD

**Issue by darkworks** [itsjavi/bootstrap-colorpicker#181]
am using below sample code 

```
<div id="cp3" class="input-group colorpicker-component">
    <input type="text" value="#00AABB" class="form-control" />
    <span class="input-group-addon"><i></i></span>
</div>
<script>
    $(function() {
        $('#cp3').colorpicker({
            color: '#AA3399',
            format: 'rgba'
        });
    });
</script>
```

i want to know how can i save the selected rgb value to 
`<input type="text" value="#00AABB" class="form-control" />`

**Comment by itsjavi** [comment]
@darkworks can you be more specific? What do you mean by `store / save` ?
You can always use events in order to know what color has been picked,
check the code of the demo where the background color of the page is changed: https://itsjavi.com/bootstrap-colorpicker/

**Comment by darkworks** [comment]
ya its solved just that by inspect element i was checking and it was not updating value it input field , however when submit we get selected color .
