### ISSUE TITLE
Use bootstrap-colorpicker in Laravel 4

### ISSUE THREAD

**Issue by adarshchacko** [itsjavi/bootstrap-colorpicker#188]
I intend to use bootstrap-colorpicker in Laravel 4 and for that I am trying to configure the composer.json. 

I tried various ways but none of them worked. At last, I tried including `"components/bootstrap": ">=2"`. That did pull a couple of files but when I used `$('#colour_picker').colorpicker(); `it stills tells me that it is unrecognised.

Did I miss anything? Where did I go wrong? Please help.

My composer.json is as  follows:

```
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"require": {
		"laravel/framework": "4.2.*",
		"elasticsearch/elasticsearch": "~1.0",
		"guzzlehttp/guzzle": "~4.0",
		"components/bootstrap": ">=2"
	},
	
	"autoload": {
		"classmap": [
			"app/commands",
			"app/controllers",
			"app/models",
			"app/database/migrations",
			"app/database/seeds",
			"app/tests/TestCase.php",
			"workbench/adarshchacko/login/src/Adarshchacko/Login"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	},
	"minimum-stability": "stable"
}
```

**Comment by itsjavi** [comment]
Hi, first, you don't have the plugin in your composer.json at all, you need to run `composer require itsjavi/bootstrap-colorpicker`.

Please note that installing the plugin via composer will only leave the repository files under the `/vendor/itsjavi/bootstrap-colorpicker` folder. It's up to you what to do with them. Usually you will need to copy the `dist` folder under your `public` laravel folder, for example:
```
mkdir -p public/assets/vendor
cp -R vendor/itsjavi/bootstrap-colorpicker/dist public/assets/vendor/bootstrap-colorpicker
```

Then you'll just need to reference the css/js files in your html like `src="assets/vendor/bootstrap-colorpicker/js/boostrap-colorpicker.min.js"`
