### ISSUE TITLE
[Features] Include images as base64 inside the CSS files

### ISSUE THREAD

**Issue by flo-sch** [itsjavi/bootstrap-colorpicker#189]
Hey,

I think it would be easier to use this plugin if the images were included as base64.
Especially when using a package manager such as npm inside a back-end framework.

Bootstrap v4 has switched to base64 images itself.

I would like to hear your point-of-view on this question, if you agree with me, then I could propose a PR for that :)

**Comment by itsjavi** [comment]
Hi, in v3 it will use CSS3 gradients instead of images + the base64 image of the alpha background
You can check it in the `develop` branch https://github.com/itsjavi/bootstrap-colorpicker/tree/develop

**Comment by flo-sch** [comment]
Excellent to hear :)
Then I guess it's better to close this issue which is not really one anymore.
