### ISSUE TITLE
Using color picker Webpack and require doesn't work

### ISSUE THREAD

**Issue by minotogna** [itsjavi/bootstrap-colorpicker#195]
I have installed the plugin using `npm install bootstrap-colorpicker --save`
and included in the module with require `require( 'bootstrap-colorpicker' )`

However I got the following error 

> Uncaught TypeError: Cannot set property 'colorpicker' of undefined
>     at bootstrap-colorpicker.js:1268
>     at $ (bootstrap-colorpicker.js:15)

Is there any configuration I'm missing (jquery is included as global object with $ )?

**Comment by n1crack** [comment]
same issue here..

**Comment by itsjavi** [comment]
fixed in v2.5.0
