### ISSUE TITLE
Color picker showing only single color

### ISSUE THREAD

**Issue by spiotr12** [itsjavi/bootstrap-colorpicker#202]
Best to see a screen:
![2017-02-06_23h25_54](https://cloud.githubusercontent.com/assets/10038964/22670964/b9776760-ecc3-11e6-9450-b188730721bc.png)

I'm using meteor + bootstrap-material-design npm package <- may be this interferes.

My code:
```
<div class="input-group colorpicker-component" id="playerColorPicker">
        <input type="text" value="#00AABB" class="form-control" />
        <span class="input-group-addon"><i></i></span>
    </div>
```
```
let colorpicker = require('bootstrap-colorpicker');

Template.table_settings_view.onRendered(function () {
	console.log('hello');
	this.$('#playerColorPicker').colorpicker({
		format: 'hex'
	});
});
```

Same issue on Chrome and Edge

Mind that it does give different HEX value and a color preview in the tine box 

Thanx for help

**Comment by spiotr12** [comment]
So I find out that I was not importing images

**Comment by itsjavi** [comment]
@spiotr12 https://github.com/itsjavi/bootstrap-colorpicker/blob/master/CONTRIBUTING.md#steps-to-submit-an-issue
