### ISSUE TITLE
include the dist files in a releases zip file

### ISSUE THREAD

**Issue by kejodion** [itsjavi/bootstrap-colorpicker#290]
please include the dist files in a releases zip file

**Comment by itsjavi** [comment]
currently, the zip is just the source code, generated by github

**Comment by KatsuroKurosaki** [comment]
I also am in favour of including dist folder on GitHub, I had to install npm in order to obtain the needed js and css files. If you don't want to include that folder anymore, I suggest updating the "Install" section in your documentation and remove the first line: Downloading a ZIP file from the releases.
Regards

**Comment by itsjavi** [comment]
I may integrate this in the future via Travis config: https://docs.travis-ci.com/user/deployment/releases/

**Comment by KatsuroKurosaki** [comment]
Hello itsjavi and thanks a lot for providing a dist zip file.
Regards

**Comment by JohnLamontagne** [comment]
Any update on this? Frustrating to have to install npm just to build this plugin.

**Comment by itsjavi** [comment]
@JohnLamontagne @kejodion  this won't be done.

you can always download the dist folder using  the npm website, you only need to know the URL (s[tack overflow is your friend](https://stackoverflow.com/questions/50933603/download-npm-dist-package-without-having-to-install-npm)) 

`https://registry.npmjs.org/bootstrap-colorpicker/-/bootstrap-colorpicker-VERSION.tgz` where VERSION is the release version in npm, e.g.:
https://registry.npmjs.org/bootstrap-colorpicker/-/bootstrap-colorpicker-3.2.0.tgz

npm also provides a nice JSON api to query versions info:
http://registry.npmjs.org/bootstrap-colorpicker/latest
http://registry.npmjs.org/bootstrap-colorpicker/3.2.0
...


You can also use wget + npm, and you don't need to build anything:

latest version:
```
wget $(npm view bootstrap-colorpicker dist.tarball)
```

specific version:
```
wget $(npm view bootstrap-colorpicker@3.0.0 dist.tarball)
```
