### ISSUE TITLE
Retrocompatibility with bootstrap v3?

### ISSUE THREAD

**Issue by itajackass** [itsjavi/bootstrap-colorpicker#300]
Hi, i tried to update from my old 3.0.0 version to latest, but plugin break my site. I'm still using bootstrap 3.x

Any chance to get it working with old bootstrap 3.x?

**Comment by itsjavi** [comment]
the only version supported for BS 3 is v2 https://github.com/itsjavi/bootstrap-colorpicker/tree/v2.x
colorpicker v3 only officially supports BS 4
