### ISSUE TITLE
Docs are down

### ISSUE THREAD

**Issue by Coronon** [itsjavi/bootstrap-colorpicker#301]
This project is awesome, but hard to use without the docs,
keep up the great work,

Coronon

**Comment by timdows** [comment]
Have the same issue
Now using the docs from source here: https://github.com/itsjavi/bootstrap-colorpicker/tree/master/src/docs

**Comment by Sleitnick** [comment]
Try this link: https://itsjavi.com//bootstrap-colorpicker/

**Comment by itsjavi** [comment]
sorry for this, now it should be fixed https://itsjavi.com/bootstrap-colorpicker/
