### ISSUE TITLE
why i can't open the API page ?

### ISSUE THREAD

**Issue by amy19900919** [itsjavi/bootstrap-colorpicker#302]
### Description

{Please write here}

### Context

- bootstrap-colorpicker version: {Please write here}
- bootstrap version: {Please write here}
- jQuery version: {Please write here}
- Browser name and version: {Please write here}
- Operative System name an version: {Please write here}

### Expected behavior

{Please write here}

### Actual behavior

{Please write here}

### Live Example

{Please write here a link to your JsFiddle example}

**Comment by Sleitnick** [comment]
The link needs to be updated. It seems to be relocated here: https://itsjavi.com//bootstrap-colorpicker/

**Comment by amy19900919** [comment]
yes,but i open the api page such as 2.x ,github jump to a 404.------------------ 原始邮件 ------------------
发件人: "Stephen Leitnick"<notifications@github.com>
发送时间: 2019年10月31日(星期四) 凌晨5:39
收件人: "itsjavi/bootstrap-colorpicker"<bootstrap-colorpicker@noreply.github.com>;
抄送: "amy19900919"<541951523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [itsjavi/bootstrap-colorpicker] why i can't open the API page ?(#302)



The link needs to be updated. It seems to be relocated here: https://itsjavi.com//bootstrap-colorpicker/
 
&mdash;

**Comment by itsjavi** [comment]
sorry for this, now it should be fixed https://itsjavi.com/bootstrap-colorpicker/
