### ISSUE TITLE
3.2.0 is not compatible with IE11

### ISSUE THREAD

**Issue by poradz** [itsjavi/bootstrap-colorpicker#309]
### Description

3.2.0 is not compatible with IE11 (Expected ':' error). ES6-shim doesn't help in this case.

### Context

- bootstrap-colorpicker version: 3.2.0
- bootstrap version: 4.3.1
- jQuery version: 3.4.1
- Browser name and version: Chrome 78.0.3904.108
- Operative System name an version: Windows 10

### Expected behavior

Works on IE11

### Actual behavior

Expected ':' error

### Live Example

https://gitdeveloper.yetiforce.com/index.php?module=Colors&parent=Settings&view=Index&block=12&fieldid=81
- open on IE11
- click 'Edit color'

**Comment by kvnvandenbrande** [comment]
Just bumped to this issue as well but do mind this error occurs only when you use the minified version!

**Comment by itsjavi** [comment]
solution: use non minified version on † IE11 † :)
