### ISSUE TITLE
Unable to import picker module

### ISSUE THREAD

**Issue by m0n9oose** [itsjavi/bootstrap-colorpicker#313]
Trying to make this lib work with webpack (Rails with webpacker gem) but no luck.

```js
import $ from 'jquery'
import 'bootstrap-colorpicker'
```

<img width="507" alt="Screenshot 2020-04-15 at 14 27 12" src="https://user-images.githubusercontent.com/1478556/79337128-42d51600-7f25-11ea-93c5-4adced1ee75f.png">

How do I import `bootrstrap-picker` to make it work with webpack?

**Comment by archonic** [comment]
@m0n9oose I'm wondering the same thing. Any tips?

**Comment by m0n9oose** [comment]
@archonic just one - find a better tool. I'm using https://github.com/Simonwep/pickr

**Comment by archonic** [comment]
There's a decent colour picker built into HTML 5 with just `<input type='color' ...>`
