### ISSUE TITLE
website can't open by my network!

### ISSUE THREAD

**Issue by kakaluote444** [itsjavi/bootstrap-colorpicker#314]
### Context
![image](https://user-images.githubusercontent.com/15668875/84219187-82257a80-ab02-11ea-937c-8177a7977c2c.png)

**Comment by kakaluote444** [comment]
https://itsjavi.com/bootstrap-colorpicker/

**Comment by itsjavi** [comment]
I am sorry, I was getting too much traffic from baidu for some reason
