### ISSUE TITLE
Disable hex input auto completing

### ISSUE THREAD

**Issue by cindi123** [itsjavi/bootstrap-colorpicker#323]
### Description

If you type characters directly into the hex input field, it will autocomplete. For example if I type 123 it will autocomplete the field by setting the value to 112233. When you try and delete some characters to change the entry it just continues to autocomplete them. Do not run the setValue() function unless the field loses focus OR there are at least 6 characters in the field. This is driving users crazy. I think you fixed this in your previous version here: https://github.com/zefoy/ngx-color-picker/issues/84. Version 3.2 doesn't have the same fix.

### Context

- bootstrap-colorpicker version: 3.2
- bootstrap version: 4
- jQuery version: jQuery v3.5.1
- Browser name and version: Firefox
- Operative System name an version: Mac OsX

### Live Example

You can see this in action on the example page for the plugin - try clearing out the hex value in the "Add complementary color swatches" example and start typing any number or letter and see what it does:
https://itsjavi.com/bootstrap-colorpicker/tutorial-p02_Advanced_Examples.html

**Comment by heliobentes** [comment]
Same issue here

**Comment by erehulka** [comment]
Have you tried
```javascript
...
$('#colorpicker').colorpicker({
  autoInputFallback: false
});
...
```

To be fair it still doesn't work for me, but you can try this setting, maybe it will somehow work for you..

**Comment by iameddz** [comment]
I've fixed this Issue for the hex-format in the update-function (Line 4653):
```
var originalColor = this.colorpicker.color._original.color;
if (originalColor.length < 7 && originalColor.startsWith('#')) {
  return;
}
```

**Comment by itsjavi** [comment]
That's how the color parsing library works. I think there is a PR from @erehulka that will solve this with an option.
thanks for taking care of that.
